from __future__ import annotations

from pathlib import Path


def generate_engineering_spec(payload: dict, output_dir: str = "output") -> Path:
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    metadata = payload["metadata"]
    path = out_dir / "engineering_spec.md"

    spec = payload["engineering_spec"]
    intake = spec["intake"]
    architecture = spec["architecture"]
    scope = spec["scope"]
    date = metadata["discovery_date"]

    decisions = "\n".join(
        f"| {d['layer']} | {d['chosen']} | {d['alternatives']} | {d['rationale']} |"
        for d in architecture["decisions"]
    )
    phases = "\n".join(
        f"| {p['phase']} | {p['deliverable']} | {p['acceptance_criteria']} | {p['timeline']} |"
        for p in scope["phases"]
    )
    env_vars = "\n".join(
        f"| {v['variable']} | {v['purpose']} | {v['who_provides']} |"
        for v in scope["environment_variables"]
    )
    limitations = "\n".join(f"- {item}" for item in scope["known_limitations"] + scope["watch_points"])
    questions = "\n".join(f"- [ ] {question}" for question in spec["open_questions"])
    agents = architecture.get("agent_architecture") or []
    data_flow = architecture.get("data_flow") or []
    diagram = _agent_diagram(agents)
    responsibilities = _agent_responsibilities(agents)
    flow = _data_flow(data_flow)
    crew_review = spec.get("crew_review")
    crew_section = ""
    if crew_review:
        crew_section = f"""
---

## CrewAI Coordination Notes

```text
{crew_review}
```
"""

    content = f"""# Engineering Spec - {spec['project_name']}

**Client:** {intake.get('client_name', 'TBD')} | **Version:** 1.0 | **Date:** {date} | **Owner:** TBD

> WARNING: This document is auto-generated. Edit freely before sharing with the engineering team.

---

## Problem Statement

{spec['problem_statement']}

---

## Framework & Stack Decisions

| Layer | Chosen | Alternatives Considered | Decision Rationale |
|---|---|---|---|
{decisions}

---

## Agent Architecture

```text
{diagram}
```

### Agent Responsibilities

{responsibilities}

---

## Data Flow

{flow}

---

## Phases & Acceptance Criteria

| Phase | Deliverable | Acceptance Criteria | Timeline |
|---|---|---|---|
{phases}

---

## Environment Variables

> WARNING: Values are NEVER stored in this document.
> Share values via secure channel (1Password, AWS Secrets Manager, or client vault).
> Client provides their own keys for their systems. The delivery team provides keys for shared infra.

| Variable | Purpose | Who Provides |
|---|---|---|
{env_vars}

---

## Known Limitations & Watch Points

{limitations}

---

## Open Questions

{questions}
{crew_section}

---

*Generated by Discovery Agent - {date} - Edit freely before sharing*
"""
    path.write_text(content, encoding="utf-8")
    return path


def _agent_diagram(agents: list[dict]) -> str:
    if not agents:
        return "Trigger -> IntakeAgent -> RetrievalAgent -> DecisionAgent -> ApprovalAgent -> Output"
    names = [agent["name"] for agent in agents]
    return " -> ".join(names)


def _agent_responsibilities(agents: list[dict]) -> str:
    if not agents:
        agents = [
            {
                "name": "IntakeAgent",
                "input": "Raw workflow input",
                "output": "Structured case profile",
                "tools": "Approved source-system connectors",
                "notes": "Keeps unknown information as open questions",
            }
        ]
    sections = []
    for agent in agents:
        sections.append(
            f"""**{agent['name']}**
- Input: {agent['input']}
- Output: {agent['output']}
- Tools: {agent['tools']}
- Notes: {agent['notes']}"""
        )
    return "\n\n".join(sections)


def _data_flow(flow: list[dict]) -> str:
    if not flow:
        flow = [
            {"step": "Trigger", "description": "The workflow starts from a manual run, webhook, or approved source-system event."},
            {"step": "Extraction", "description": "The intake agent converts raw inputs into structured data and open questions."},
            {"step": "Retrieval", "description": "ChromaDB retrieves relevant records or reference cases using local embeddings."},
            {"step": "Processing", "description": "Specialized agents reason over the case and prepare recommendations."},
            {"step": "Output", "description": "Approved outputs are written back to the selected client systems."},
        ]
    return "\n".join(f"{index}. **{item['step']}** - {item['description']}" for index, item in enumerate(flow, start=1))
