from __future__ import annotations

from datetime import datetime
from pathlib import Path


def generate_engineering_spec(payload: dict, output_dir: str = "output") -> Path:
    now = datetime.now()
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"engineering_spec_{now:%Y-%m-%d_%H-%M}.md"

    spec = payload["engineering_spec"]
    intake = spec["intake"]
    architecture = spec["architecture"]
    scope = spec["scope"]
    date = now.strftime("%Y-%m-%d")

    decisions = "\n".join(
        f"| {d['layer']} | {d['chosen']} | {d['alternatives']} | {d['rationale']} |"
        for d in architecture["decisions"]
    )
    phases = "\n".join(
        f"| {p['phase']} | {p['deliverable']} | {p['acceptance_criteria']} | {p['timeline']} |"
        for p in scope["phases"]
    )
    env_vars = "\n".join(
        f"| {v['variable']} | {v['purpose']} | {v['who_provides']} |"
        for v in scope["environment_variables"]
    )
    limitations = "\n".join(f"- {item}" for item in scope["known_limitations"] + scope["watch_points"])
    questions = "\n".join(f"- [ ] {question}" for question in spec["open_questions"])
    crew_review = spec.get("crew_review")
    crew_section = ""
    if crew_review:
        crew_section = f"""
---

## CrewAI Coordination Notes

```text
{crew_review}
```
"""

    content = f"""# Engineering Spec - {spec['project_name']}

**Client:** {intake.get('client_name', 'TBD')} | **Version:** 1.0 | **Date:** {date} | **Owner:** TBD

> WARNING: This document is auto-generated. Edit freely before sharing with the engineering team.

---

## Problem Statement

{spec['problem_statement']}

---

## Framework & Stack Decisions

| Layer | Chosen | Alternatives Considered | Decision Rationale |
|---|---|---|---|
{decisions}

---

## Agent Architecture

```text
Transcript -> IntakeParser -> SolutionArchitect -> ScopeEstimator -> ProposalDrafter
                         |              |
                         v              v
                    Structured JSON   RAG Search
                         |              |
                         +------> Document Generators
```

### Agent Responsibilities

**IntakeParser**
- Input: Raw transcript
- Output: Structured JSON with client, problem, tools, integrations, urgency, and complexity
- Tools: None
- Notes: Keeps missing information as TBD instead of inventing facts

**SolutionArchitect**
- Input: Transcript and intake JSON
- Output: Architecture summary, stack decisions, and similar case references
- Tools: rag_search
- Notes: Chooses orchestration and model based on case complexity

**ScopeEstimator**
- Input: Intake JSON and architecture decisions
- Output: Phases, acceptance criteria, limitations, watch points, infra cost, env vars
- Tools: None
- Notes: Timelines never exceed 8 weeks; larger efforts are split into phases

**ProposalDrafter**
- Input: Intake, architecture, and scope payloads
- Output: Client proposal content and engineering spec content
- Tools: pdf_generator, markdown_generator
- Notes: Client proposal omits technical stack and environment variables

---

## Data Flow

1. **Trigger** - Manual transcript input or live audio capture.
2. **Extraction** - IntakeParser converts transcript text into structured JSON.
3. **Retrieval** - RAG searches `knowledge_base/` with `n_results=3` using local ChromaDB embeddings.
4. **Processing** - SolutionArchitect defines technical choices, ScopeEstimator converts complexity into phases, ProposalDrafter prepares final content.
5. **Output** - PDF is written via WeasyPrint and Markdown is written directly to `output/`.

---

## Phases & Acceptance Criteria

| Phase | Deliverable | Acceptance Criteria | Timeline |
|---|---|---|---|
{phases}

---

## Environment Variables

> WARNING: Values are NEVER stored in this document.
> Share values via secure channel (1Password, AWS Secrets Manager, or client vault).
> Client provides their own keys for their systems. Zaigo provides keys for shared infra.

| Variable | Purpose | Who Provides |
|---|---|---|
{env_vars}

---

## Known Limitations & Watch Points

{limitations}

---

## Open Questions

{questions}
{crew_section}

---

*Generated by Discovery Agent - {date} - Edit freely before sharing*
"""
    path.write_text(content, encoding="utf-8")
    return path
